[package]
name = "oracles"
edition = "2024"

[dependencies]
pyth = { git = "https://github.com/solendprotocol/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }
switchboard = { git = "https://github.com/switchboard-xyz/sui.git", subdir = "on_demand/", rev = "mainnet" }
