[package]
name = "setup"
edition = "2024.beta"

[dependencies]
suilend = { local = "../../contracts/suilend" }
cvlm = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "cvlm", rev = "sui-v1.55.0" }
certora_sui_summaries = { git = "https://github.com/Certora/cvl-move-proto.git", subdir = "certora_sui_summaries",  rev = "sui-v1.55.0" }

[addresses]
setup = "0x0"