[package]
name = "vaults"
edition = "2024"
published-at = "0x27a909073ccdb6d5d20675da12dcc888b4fe5374edef0f0b81588a6f432fd74e"

[dependencies]
steamm = { git = "https://github.com/suilend/steamm-public.git", subdir = "contracts/steamm", rev = "main" }
suilend = { local = "../suilend" } 

[dependencies.Pyth]
git = "https://github.com/solendprotocol/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "98e218c64bb75cf1350eb7b021e1ffcc3aedfd62"

[addresses]
vaults = "0x27a909073ccdb6d5d20675da12dcc888b4fe5374edef0f0b81588a6f432fd74e"

[dev-dependencies]

[dev-addresses]
