[package]
name = "vaults"
edition = "2024"
published-at = "0x3a3aec2b9216e9ec41c829d66f24bf920873e014c6b1b058f024c293a58d618c"

[dependencies]
steamm = { git = "https://github.com/suilend/steamm-public.git", subdir = "contracts/steamm", rev = "main" }
suilend = { local = "../suilend" } 

[dependencies.Pyth]
git = "https://github.com/solendprotocol/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "98e218c64bb75cf1350eb7b021e1ffcc3aedfd62"

[addresses]
vaults = "0x3a3aec2b9216e9ec41c829d66f24bf920873e014c6b1b058f024c293a58d618c"

[dev-dependencies]

[dev-addresses]
