[package]
name = "suilend"
version = "0.0.1"
published-at = "0xdf48a8edf980a895be1719a74801308ebf634fb4d759017f7650d96196bd14e8"
edition = "2024"

[dependencies.Pyth]
git = "https://github.com/solendprotocol/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"

[dependencies.liquid_staking]
git = "https://github.com/solendprotocol/liquid-staking.git"
subdir = "contracts"
rev = "main"

[dependencies.sprungsui]
local = "../sprungsui"

[addresses]
sui = "0x2"
# suilend = "0x0"
suilend = "0x16273556ccb509904a6c31b3a2d3c73cf763665a945b41798ceae92de95893dc"
