[package]
name = "suilend"
edition = "2024"

[dependencies]
liquid_staking = { git = "https://github.com/solendprotocol/liquid-staking.git", subdir = "contracts", rev = "main" }
pyth = { git = "https://github.com/solendprotocol/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }
sprungsui = { local = "../sprungsui" }
sui_system = { system = "sui_system" }
switchboard = { git = "https://github.com/switchboard-xyz/sui.git", subdir = "on_demand/", rev = "mainnet" }
