[package]
name = "strategy_wrapper"
version = "0.0.1"
published-at = "0xb4e22255bb2ef58c4451eaf5a93135bb9acac58951b1755f1d2aaaad675a0f47"
edition = "2024.beta"

[dependencies]
suilend = { local = "../suilend" } 

[addresses]
strategy_wrapper = "0x0" 


